### ISSUE TITLE
lein install-db throws NullPointerException

### ISSUE THREAD

**Issue by theronic** [bellkev/dacom#3]
Datomic Pro Starter is running on `datomic:dev://localhost:4334/<DB-NAME>`. Running `lein install-db` crashes with a NullPointerException after retrieving all dependencies:

```
PS D:\projects\dacom> lein install-db
    Exception in thread "main" java.lang.NullPointerException, compiling:(db.clj:118:3)
            at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3463)
            at clojure.lang.Compiler$DefExpr.eval(Compiler.java:408)
            at clojure.lang.Compiler.eval(Compiler.java:6624)
            at clojure.lang.Compiler.load(Compiler.java:7064)
            at clojure.lang.RT.loadResourceScript(RT.java:370)
            at clojure.lang.RT.loadResourceScript(RT.java:361)
            at clojure.lang.RT.load(RT.java:440)
            at clojure.lang.RT.load(RT.java:411)
            at clojure.core$load$fn__5018.invoke(core.clj:5530)
            at clojure.core$load.doInvoke(core.clj:5529)
            at clojure.lang.RestFn.invoke(RestFn.java:408)
            at clojure.core$load_one.invoke(core.clj:5336)
            at clojure.core$load_lib$fn__4967.invoke(core.clj:5375)
            at clojure.core$load_lib.doInvoke(core.clj:5374)
            at clojure.lang.RestFn.applyTo(RestFn.java:142)
            at clojure.core$apply.invoke(core.clj:619)
            at clojure.core$load_libs.doInvoke(core.clj:5413)
            at clojure.lang.RestFn.applyTo(RestFn.java:137)
            at clojure.core$apply.invoke(core.clj:619)
            at clojure.core$require.doInvoke(core.clj:5496)
            at clojure.lang.RestFn.invoke(RestFn.java:408)
            at user$eval4438$fn__4440.invoke(form-init799516097382537019.clj:1)
            at user$eval4438.invoke(form-init799516097382537019.clj:1)
            at clojure.lang.Compiler.eval(Compiler.java:6619)
            at clojure.lang.Compiler.eval(Compiler.java:6609)
            at clojure.lang.Compiler.load(Compiler.java:7064)
            at clojure.lang.Compiler.loadFile(Compiler.java:7020)
            at clojure.main$load_script.invoke(main.clj:294)
            at clojure.main$init_opt.invoke(main.clj:299)
            at clojure.main$initialize.invoke(main.clj:327)
            at clojure.main$null_opt.invoke(main.clj:362)
            at clojure.main$main.doInvoke(main.clj:440)
            at clojure.lang.RestFn.invoke(RestFn.java:421)
            at clojure.lang.Var.invoke(Var.java:419)
            at clojure.lang.AFn.applyToHelper(AFn.java:163)
            at clojure.lang.Var.applyTo(Var.java:532)
            at clojure.main.main(main.java:37)
    Caused by: java.lang.NullPointerException
            at java.util.UUID.fromString(UUID.java:192)
            at datomic.cluster$val_key__GT_uuid.invoke(cluster.clj:21)
            at datomic.log$find_log.invoke(log.clj:526)
            at datomic.peer$load_db_from_basis.invoke(peer.clj:95)
            at datomic.peer.Connection$fn__7355$load_db__7361.invoke(peer.clj:202)
            at datomic.peer.Connection$fn__7355.invoke(peer.clj:203)
            at datomic.peer.Connection.create_connection_state(peer.clj:187)
            at datomic.peer$create_connection$reconnect_fn__7400.invoke(peer.clj:389)
            at datomic.peer$create_connection.invoke(peer.clj:390)
            at datomic.peer$get_connection$fn__7450$fn__7452.invoke(peer.clj:542)
            at datomic.peer$get_connection$fn__7450.invoke(peer.clj:539)
            at datomic.peer$get_connection.invoke(peer.clj:536)
            at datomic.peer$connect_uri.invoke(peer.clj:600)
            at clojure.lang.Var.invoke(Var.java:415)
            at datomic.Peer.connect(Peer.java:110)
            at datomic.api$connect.invoke(api.clj:15)
            at clojure.lang.AFn.applyToHelper(AFn.java:161)
            at clojure.lang.AFn.applyTo(AFn.java:151)
            at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3458)
            ... 36 more
    Error encountered performing task 'run' with profile(s): 'db'
    Suppressed exit
```

**Comment by theronic** [comment]
It was because `dacom/config/dev-config.edn` had `datomic:free...` as the protocol, but if I change it to `datomic:dev...` like the Datomic transactor I'm running, then it throws the following exception:

PS D:\projects\dacom> lein install-db
    Exception in thread "main" java.lang.IllegalArgumentException: :db.error/unsupported-protocol Unsupported protocol :dev
            at datomic.error$arg.invoke(error.clj:55)
            at datomic.error$arg.invoke(error.clj:53)
            at datomic.coordination$fn__6317.invoke(coordination.clj:80)...

**Comment by theronic** [comment]
Ah, if you have Datomic Pro, you need to update your dependency in `project.clj` and add a repository, since the `datomic-pro` package is not in the public Maven repo:

```
:dependencies [ ... [com.datomic/datomic-pro "0.9.4556"]]

:repositories {"my.datomic.com" {:url "https://my.datomic.com/repo"
                             :username "<email>"
                             :password "<password>"}}
```

**Comment by alantriesagain** [comment]
+1
