### ISSUE TITLE
Exception when running install-db

### ISSUE THREAD

**Issue by Conaws** [bellkev/dacom#8]
Here is the full message -- this happened both on cloning this repo and with the template 

Exception in thread "main" java.lang.NullPointerException, compiling:(db.clj:118:3)
    at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3463)
    at clojure.lang.Compiler$DefExpr.eval(Compiler.java:408)
    at clojure.lang.Compiler.eval(Compiler.java:6624)
    at clojure.lang.Compiler.load(Compiler.java:7064)
    at clojure.lang.RT.loadResourceScript(RT.java:370)
    at clojure.lang.RT.loadResourceScript(RT.java:361)
    at clojure.lang.RT.load(RT.java:440)
    at clojure.lang.RT.load(RT.java:411)
    at clojure.core$load$fn__5018.invoke(core.clj:5530)
    at clojure.core$load.doInvoke(core.clj:5529)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5336)
    at clojure.core$load_lib$fn__4967.invoke(core.clj:5375)
    at clojure.core$load_lib.doInvoke(core.clj:5374)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$load_libs.doInvoke(core.clj:5413)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$require.doInvoke(core.clj:5496)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at user$eval4438$fn__4440.invoke(form-init6599812460272478650.clj:1)
    at user$eval4438.invoke(form-init6599812460272478650.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6619)
    at clojure.lang.Compiler.eval(Compiler.java:6609)
    at clojure.lang.Compiler.load(Compiler.java:7064)
    at clojure.lang.Compiler.loadFile(Compiler.java:7020)
    at clojure.main$load_script.invoke(main.clj:294)
    at clojure.main$init_opt.invoke(main.clj:299)
    at clojure.main$initialize.invoke(main.clj:327)
    at clojure.main$null_opt.invoke(main.clj:362)
    at clojure.main$main.doInvoke(main.clj:440)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:419)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.main.main(main.java:37)
Caused by: java.lang.NullPointerException
    at java.util.UUID.fromString(UUID.java:192)
    at datomic.cluster$val_key__GT_uuid.invoke(cluster.clj:21)
    at datomic.log$find_log.invoke(log.clj:526)
    at datomic.peer$load_db_from_basis.invoke(peer.clj:95)
    at datomic.peer.Connection$fn__7355$load_db__7361.invoke(peer.clj:202)
    at datomic.peer.Connection$fn__7355.invoke(peer.clj:203)
    at datomic.peer.Connection.create_connection_state(peer.clj:187)
    at datomic.peer$create_connection$reconnect_fn__7400.invoke(peer.clj:389)
    at datomic.peer$create_connection.invoke(peer.clj:390)
    at datomic.peer$get_connection$fn__7450$fn__7452.invoke(peer.clj:542)
    at datomic.peer$get_connection$fn__7450.invoke(peer.clj:539)
    at datomic.peer$get_connection.invoke(peer.clj:536)
    at datomic.peer$connect_uri.invoke(peer.clj:600)
    at clojure.lang.Var.invoke(Var.java:415)
    at datomic.Peer.connect(Peer.java:110)
    at datomic.api$connect.invoke(api.clj:15)
    at clojure.lang.AFn.applyToHelper(AFn.java:161)
    at clojure.lang.AFn.applyTo(AFn.java:151)
    at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3458)
    ... 36 more
Error encountered performing task 'run' with profile(s): 'db'
Suppressed exit

**Comment by Conaws** [comment]
I'll add that I'd be thrilled if you -- or someone else, revisited this project, particularly with figwheel and om-next (maybe devcards too), I've been having a bunch of trouble trying to figure out how I can compile an app that connects to datomic without my system trying to connect to the production db during compilation.  Was hoping this example could help me figure that out.
